baseURL = 'http://hopmannconsulting.com'
languageCode = 'en-us'
title = 'Hopmann Consulting'
theme = 'spectral'
[params]
    fancytitle = 'Hopmann Consulting'
    description = 'Strategic and Execution Excellence'


[params.contact]
  email = 'tim@hopmannconsulting.com'